name: CD

on:
  push:
    branches:
      - main
      - beta

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 15
          cache: "pnpm"

      # pnpm stuff
      - name: pnpm - install
        run: pnpm install
      - name: lint
        run: pnpm lint
      - name: build
        run: pnpm build # bae — before everything else
      - name: test
        run: pnpm t

      # - name: coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}

      # publish to npm
      - name: release
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          version: pnpm version-packages
          commit: "chore: version packages"
          title: "chore: version packages"
